### ISSUE TITLE
add new icons to r6operators.marcopixel.eu

### ISSUE THREAD

**Issue by Fabian-Kleine** [marcopixel/r6operators#53]
The new icons after Solis are not on the r6operators.marcopixel.eu website which I used to easily download them.
It would be very nice if you could also add them there because it makes downloading them a lot easier compared to GitHub.

**Comment by marcopixel** [comment]
@Fabian-Kleine

The old website couldn't be updated since it was severely outdated codewise (needed a lot of work to migrate to the newest node, etc..) and that was the reason why i've only published it on Github so far. But recently i've got a bit of time and motivation to tackle this project and since today it's up-to-date again with a updated look and new features :)

You can still find it at https://r6operators.marcopixel.eu/.
